// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGpF_ZqSbQtiH2ZU0yza_qZDeUgwE7Wus',
    appId: '1:346730783451:web:e116392bed2ed01c7d22fe',
    messagingSenderId: '346730783451',
    projectId: 'mahdi-notes-app',
    authDomain: 'mahdi-notes-app.firebaseapp.com',
    storageBucket: 'mahdi-notes-app.firebasestorage.app',
    measurementId: 'G-3FLX3DDPGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE35xPpfI6JTJOMz_U-aslY1n0GQrVh80',
    appId: '1:346730783451:android:969a3f980bf87aef7d22fe',
    messagingSenderId: '346730783451',
    projectId: 'mahdi-notes-app',
    storageBucket: 'mahdi-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQa2lTdlFIEPr0My1iWEWi8QNenPbPHn0',
    appId: '1:346730783451:ios:be65bd24d5adeb967d22fe',
    messagingSenderId: '346730783451',
    projectId: 'mahdi-notes-app',
    storageBucket: 'mahdi-notes-app.firebasestorage.app',
    iosBundleId: 'com.almalikofficial.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQa2lTdlFIEPr0My1iWEWi8QNenPbPHn0',
    appId: '1:346730783451:ios:be65bd24d5adeb967d22fe',
    messagingSenderId: '346730783451',
    projectId: 'mahdi-notes-app',
    storageBucket: 'mahdi-notes-app.firebasestorage.app',
    iosBundleId: 'com.almalikofficial.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGpF_ZqSbQtiH2ZU0yza_qZDeUgwE7Wus',
    appId: '1:346730783451:web:32b5eb9b0ab4b64b7d22fe',
    messagingSenderId: '346730783451',
    projectId: 'mahdi-notes-app',
    authDomain: 'mahdi-notes-app.firebaseapp.com',
    storageBucket: 'mahdi-notes-app.firebasestorage.app',
    measurementId: 'G-88X5G5JG77',
  );
}
